apiVersion: v1
kind: Pod
metadata: 
  name: mysql-vol
spec:
  containers:
    - name: mysql-vol
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: employees
      ports:
        - name: mysql-vol
          containerPort: 3306
          protocol: TCP
      volumeMounts:
        - name: mysql-vol
          mountPath: /var/lib/mysql
  volumes: 
    - name: mysql-vol
      emptyDir:
