---
apiVersion: v1
kind: ReplicaSet
metadata: 
  name: nginx-rs
  labels:
    app: nginx
    tag: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tag: dev
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        tag: dev
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: nginx-web-port
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
  type: LoadBalancer
  selector:
     app: nginx
     tag: dev
  ports:
    - name: nginx-web-port
      port: 35000
      targetPort: 80
      protocol: TCP
    
    
        
      